export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const LOAD_TEAMS_FAILURE = 'LOAD_TEAMS_FAILURE';
export const LOAD_MATCHES_SUCCESS = 'LOAD_MATCHES_SUCCESS';
export const LOAD_MATCHES_FAILURE = 'LOAD_MATCHES_FAILURE';
export const NEW_SEASON_STARTED = 'NEW_SEASON_STARTED';
export const SIM_WEEK_SUCCESS = 'SIM_WEEK_SUCCESS';
export const ADVANCE_WEEK = 'ADVANCE_WEEK';
export const INIT = '@@redux/INIT';
